FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install && npm run build
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node","server.js"]
